// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	jwt_manager "ebank/pkg/jwt_manager"

	mock "github.com/stretchr/testify/mock"

	model "ebank/internal/model"
)

// JWTManager is an autogenerated mock type for the JWTManager type
type JWTManager struct {
	mock.Mock
}

type JWTManager_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTManager) EXPECT() *JWTManager_Expecter {
	return &JWTManager_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: user
func (_m *JWTManager) Generate(user model.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(model.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(model.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type JWTManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - user model.User
func (_e *JWTManager_Expecter) Generate(user interface{}) *JWTManager_Generate_Call {
	return &JWTManager_Generate_Call{Call: _e.mock.On("Generate", user)}
}

func (_c *JWTManager_Generate_Call) Run(run func(user model.User)) *JWTManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.User))
	})
	return _c
}

func (_c *JWTManager_Generate_Call) Return(_a0 string, _a1 error) *JWTManager_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManager_Generate_Call) RunAndReturn(run func(model.User) (string, error)) *JWTManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: accessToken
func (_m *JWTManager) Verify(accessToken string) (*jwt_manager.UserClaims, error) {
	ret := _m.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *jwt_manager.UserClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwt_manager.UserClaims, error)); ok {
		return rf(accessToken)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt_manager.UserClaims); ok {
		r0 = rf(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt_manager.UserClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManager_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type JWTManager_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - accessToken string
func (_e *JWTManager_Expecter) Verify(accessToken interface{}) *JWTManager_Verify_Call {
	return &JWTManager_Verify_Call{Call: _e.mock.On("Verify", accessToken)}
}

func (_c *JWTManager_Verify_Call) Run(run func(accessToken string)) *JWTManager_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *JWTManager_Verify_Call) Return(_a0 *jwt_manager.UserClaims, _a1 error) *JWTManager_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManager_Verify_Call) RunAndReturn(run func(string) (*jwt_manager.UserClaims, error)) *JWTManager_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTManager creates a new instance of JWTManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTManager {
	mock := &JWTManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
